base_url: "http://help.bet365data.com/"
api_key_env: CROWDIN_DOCUSAURUS_API_KEY
preserve_hierarchy: true
files:
  - source: /bet365/**/*.md
    ignore:
      - /bet365/ja
      - /bet365/fr
      - /bet365/cn
      - /bet365/en
    translation: /bet365/%two_letters_code%/**/%original_file_name%
